Repository artsy/positron, pull requests merged in 2018-11, with the labels that each got.

#1777 Add UI for uploading Display video cover images
  src/client/apps/display/query.js
  src/client/apps/settings/client/curations/display/components/canvas/canvas_images.jsx
  src/client/apps/settings/client/curations/display/index.styl
  src/client/apps/settings/client/curations/display/test/components/canvas/canvas_images.test.js
Labels: In progress, Jira Synced

#1778 Release
  src/client/apps/display/query.js
  src/client/apps/settings/client/curations/display/components/canvas/canvas_images.jsx
  src/client/apps/settings/client/curations/display/index.styl
  src/client/apps/settings/client/curations/display/test/components/canvas/canvas_images.test.js
Labels: In progress

#1779 Impression pixel
  src/api/apps/articles/model/schema.coffee
  src/api/apps/articles/test/model/index/persistence.test.coffee
  src/client/apps/edit/components/admin/components/sponsor.jsx
  src/client/apps/edit/components/admin/test/components/sponsor.test.js
Labels: In progress, Jira Synced

#1780 Deploy
  src/api/apps/articles/model/schema.coffee
  src/api/apps/articles/test/model/index/persistence.test.coffee
  src/client/apps/edit/components/admin/components/sponsor.jsx
  src/client/apps/edit/components/admin/test/components/sponsor.test.js
Labels: In progress

#1788 Video credits allow linebreaks
  src/client/apps/edit/components/content/article_layouts/video.jsx
  src/client/components/draft/paragraph/paragraph.tsx
  src/client/components/draft/paragraph/test/paragraph.test.tsx
  src/client/components/draft/paragraph/utils/convert.tsx
  src/client/components/draft/paragraph/utils/test/convert.test.tsx
Labels: In progress, Jira Synced

#1789 Release
  package.json
  renovate.json
  src/client/apps/edit/components/content/article_layouts/video.jsx
  src/client/components/draft/paragraph/paragraph.tsx
  src/client/components/draft/paragraph/test/paragraph.test.tsx
  src/client/components/draft/paragraph/utils/convert.tsx
  src/client/components/draft/paragraph/utils/test/convert.test.tsx
  yarn.lock
Labels: In progress

#1781 upgrade to node 10
  .circleci/config.yml
  Dockerfile
  package.json
Labels: In progress, Merge On Green

#1793 add new has_gradient_overlay property
  src/api/apps/graphql/schemas/display.js
  src/client/apps/settings/client/curations/display/components/canvas/index.jsx
  src/client/apps/settings/client/curations/display/test/components/canvas/index.test.js
Labels: In progress, Jira Synced

#1796 Deploy
  .circleci/config.yml
  Dockerfile
  package.json
  src/api/apps/graphql/schemas/display.js
  src/client/apps/settings/client/curations/display/components/canvas/index.jsx
  src/client/apps/settings/client/curations/display/test/components/canvas/index.test.js
  yarn.lock
Labels: In progress

#1799 Bump reaction to 8.9.1
  package.json
  src/client/apps/edit/components/content/sections/images/components/image_set.jsx
  src/client/apps/edit/components/content/sections/images/test/image_set.test.js
  src/client/apps/edit/components/content/sections/images/test/index.test.js
  yarn.lock
Labels: In progress
