Repository artsy/positron, pull requests merged in 2018-08, with the labels that each got.

#1731 @xtina-starr => Add palette, TextUrlInput updates
  package.json
  src/client/apps/edit/components/admin/components/image_upload.coffee
  src/client/apps/edit/components/content/sections/header/test/index.test.js
  src/client/apps/edit/components/content/sections/text/test/links.test.js
  src/client/apps/settings/client/curations/display/test/components/canvas/canvas_images.test.js
  src/client/components/image_upload_form/index.styl
  src/client/components/remove_button/index.jsx
  src/client/components/rich_text/components/input_url.jsx
  src/client/components/rich_text/index.styl
  src/client/components/rich_text/test/components/input_url.test.js
  yarn.lock
Labels: In progress

#1733 Paragraph utils
  package.json
  src/api/apps/articles/test/integration.test.coffee
  src/client/components/draft/paragraph/utils/__tests__/convert.test.tsx
  src/client/components/draft/paragraph/utils/__tests__/decorators.test.tsx
  src/client/components/draft/paragraph/utils/__tests__/links.test.ts
  src/client/components/draft/paragraph/utils/__tests__/utils.test.ts
  src/client/components/draft/paragraph/utils/convert.tsx
  src/client/components/draft/paragraph/utils/decorators.tsx
  src/client/components/draft/paragraph/utils/links.ts
  src/client/components/draft/paragraph/utils/typings.ts
  src/client/components/draft/paragraph/utils/utils.ts
  yarn.lock
Labels: In progress

#1732 @xtina-starr => Move PlainText to components/draft
  src/client/apps/edit/components/content/article_layouts/news.jsx
  src/client/apps/edit/components/content/article_layouts/series.jsx
  src/client/apps/edit/components/content/article_layouts/test/series.test.js
  src/client/apps/edit/components/content/article_layouts/test/video.test.js
  src/client/apps/edit/components/content/article_layouts/video.jsx
  src/client/apps/edit/components/content/sections/header/index.jsx
  src/client/apps/edit/components/content/sections/header/test/index.test.js
  src/client/apps/settings/client/curations/display/test/components/canvas/canvas_text.test.js
  src/client/components/character_limit/index.jsx
  src/client/components/character_limit/test/index.test.js
  src/client/components/draft/plain_text/__tests__/plain_text.test.jsx
  src/client/components/draft/plain_text/plain_text.jsx
Labels: In progress

#1730 [Toolchain] Update to Typescript 3
  .babelrc
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  .vscode/tasks.json
  package.json
  src/api/apps/articles/test/integration.test.coffee
  tsconfig.json
  tslint.json
  yarn.lock
Labels: In progress, Ready for Review

#1734 @damassi => Install prettier, update vscode settings
  .vscode/settings.json
  package.json
  yarn.lock
Labels: In progress

#1735 @damassi => API tests can use Jest
  package.json
  scripts/test.sh
  src/api/apps/graphql/test/integration.spec.js
  src/api/apps/graphql/test/resolvers.spec.js
  src/api/apps/search/test/routes.test.js
  src/api/apps/sessions/test/integration.spec.js
  src/api/apps/sessions/test/model.spec.js
  src/client/apps/edit/components/error/test/index.test.js
  src/client/apps/edit/components/test/edit_container.test.js
  src/client/components/draft/paragraph/utils/decorators.tsx
  src/client/components/draft/paragraph/utils/test/convert.test.tsx
  src/client/components/draft/paragraph/utils/test/decorators.test.tsx
  src/client/components/draft/paragraph/utils/test/links.test.ts
  src/client/components/draft/paragraph/utils/test/utils.test.ts
  src/client/components/draft/paragraph/utils/typings.ts
  src/client/components/draft/plain_text/test/plain_text.test.jsx
  src/client/reducers/test/editReducer.test.js
Labels: In progress

#1736 @l2succes => Remove babel-rewire dependency
  .babelrc
  package.json
  src/api/apps/articles/test/model/index/index.test.coffee
  src/api/apps/articles/test/model/index/persistence.test.coffee
  src/client/apps/articles_list/routes.coffee
  src/client/apps/articles_list/routes.js
  src/client/apps/articles_list/test/routes.test.coffee
  src/client/apps/articles_list/test/routes.test.js
  yarn.lock
Labels: In progress, Merge On Green

#1737 Release
  .babelrc
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  .vscode/tasks.json
  README.md
  doc/api.md
  package.json
  scripts/test.sh
  src/api/apps/articles/test/integration.test.coffee
  src/api/apps/articles/test/model/index/index.test.coffee
  src/api/apps/articles/test/model/index/persistence.test.coffee
  src/api/apps/graphql/test/integration.spec.js
  src/api/apps/graphql/test/resolvers.spec.js
  src/api/apps/search/test/routes.test.js
  src/api/apps/sessions/test/integration.spec.js
  src/api/apps/sessions/test/model.spec.js
  src/client/apps/articles_list/routes.coffee
  src/client/apps/articles_list/routes.js
  src/client/apps/articles_list/test/routes.test.coffee
  src/client/apps/articles_list/test/routes.test.js
  src/client/apps/edit/components/admin/components/image_upload.coffee
  src/client/apps/edit/components/content/article_layouts/news.jsx
  src/client/apps/edit/components/content/article_layouts/series.jsx
  src/client/apps/edit/components/content/article_layouts/test/series.test.js
  src/client/apps/edit/components/content/article_layouts/test/video.test.js
  src/client/apps/edit/components/content/article_layouts/video.jsx
  src/client/apps/edit/components/content/sections/header/index.jsx
  src/client/apps/edit/components/content/sections/header/test/index.test.js
  src/client/apps/edit/components/content/sections/text/test/links.test.js
  src/client/apps/edit/components/error/test/index.test.js
  src/client/apps/edit/components/test/edit_container.test.js
  src/client/apps/settings/client/curations/display/test/components/canvas/canvas_images.test.js
  src/client/apps/settings/client/curations/display/test/components/canvas/canvas_text.test.js
  src/client/components/character_limit/index.jsx
  src/client/components/character_limit/test/index.test.js
  src/client/components/draft/paragraph/utils/convert.tsx
  src/client/components/draft/paragraph/utils/decorators.tsx
  src/client/components/draft/paragraph/utils/links.ts
  src/client/components/draft/paragraph/utils/test/convert.test.tsx
  src/client/components/draft/paragraph/utils/test/decorators.test.tsx
  src/client/components/draft/paragraph/utils/test/links.test.ts
  src/client/components/draft/paragraph/utils/test/utils.test.ts
  src/client/components/draft/paragraph/utils/typings.ts
  src/client/components/draft/paragraph/utils/utils.ts
  src/client/components/draft/plain_text/plain_text.jsx
  src/client/components/draft/plain_text/test/plain_text.test.jsx
  src/client/components/image_upload_form/index.styl
  src/client/components/remove_button/index.jsx
  src/client/components/rich_text/components/input_url.jsx
  src/client/components/rich_text/index.styl
  src/client/components/rich_text/test/components/input_url.test.js
  src/client/reducers/test/editReducer.test.js
  tsconfig.json
  tslint.json
  yarn.lock
Labels: In progress
