Repository artsy/positron, pull requests merged in 2018-12, with the labels that each got.

#1770 Setup Hokusai
  .circleci/config.yml
  .circleci/setup_heroku.sh
  .dockerignore
  .env.example
  Dockerfile
  README.md
  conf/nginx.conf
  conf/positron-backend.conf
  docker-compose.yml
  hokusai/build.yml
  hokusai/config.yml
  hokusai/development.yml
  hokusai/production.yml
  hokusai/staging.yml
  hokusai/test.yml
  package.json
  scripts/production.sh
  scripts/publish-assets.sh
  scripts/sync-staging-production-mongo.sh
  scripts/test.sh
Labels: In progress

#1812 Release
  .circleci/config.yml
  .circleci/setup_heroku.sh
  .dockerignore
  .env.example
  Dockerfile
  README.md
  conf/nginx.conf
  conf/positron-backend.conf
  docker-compose.yml
  hokusai/build.yml
  hokusai/config.yml
  hokusai/development.yml
  hokusai/production.yml
  hokusai/staging.yml
  hokusai/test.yml
  package.json
  scripts/production.sh
  scripts/publish-assets.sh
  scripts/sync-staging-production-mongo.sh
  scripts/test.sh
  yarn.lock
Labels: In progress

#1798 [FEATURE Video] Add a field that allows the video duration to be edited
  src/client/apps/edit/components/admin/components/article/article_publish_date.jsx
  src/client/apps/edit/components/admin/components/article/article_video_release_date.tsx
  src/client/apps/edit/components/admin/components/article/button_medium.tsx
  src/client/apps/edit/components/admin/components/article/index.jsx
  src/client/apps/edit/components/admin/test/components/article/index.test.js
  src/client/apps/edit/components/content/article_layouts/test/video.test.js
  src/client/apps/edit/components/content/article_layouts/video.jsx
Labels: In progress, Jira Synced

#1811 Add @types/styled-system
  package.json
  yarn.lock
Labels: In progress, Jira Synced

#1815 Migrate cronjobs to K8s
  hokusai/production.yml
  hokusai/staging.yml
Labels: In progress

#1813 PLATFORM-1080: Configure data dog tracing for positron
  .env.example
  hokusai/production.yml
  hokusai/staging.yml
  package.json
  scripts/start.sh
  src/boot.js
  src/tracer.ts
  yarn.lock
Labels: Jira Synced

#1818 Deploy
  .env.example
  hokusai/production.yml
  hokusai/staging.yml
  package.json
  scripts/start.sh
  src/boot.js
  src/client/apps/edit/components/admin/components/article/article_publish_date.jsx
  src/client/apps/edit/components/admin/components/article/article_video_release_date.tsx
  src/client/apps/edit/components/admin/components/article/button_medium.tsx
  src/client/apps/edit/components/admin/components/article/index.jsx
  src/client/apps/edit/components/admin/test/components/article/index.test.js
  src/client/apps/edit/components/content/article_layouts/test/video.test.js
  src/client/apps/edit/components/content/article_layouts/video.jsx
  src/tracer.ts
  yarn.lock
Labels: Jira Synced

#1814 small changes to readme
  README.md
Labels: In progress

#1825 allow social embeds on feature and standard articles
  src/client/apps/edit/components/content/section_tool/index.jsx
  src/client/apps/edit/components/content/section_tool/test/index.test.js
Labels: Jira Synced
