Repository artsy/positron, pull requests merged in 2018-10, with the labels that each got.

#1762 Paragraph/Sections QA
  .eslintrc
  package.json
  src/client/apps/display/test/routes.test.js
  src/client/apps/edit/components/content/section_controls/index.jsx
  src/client/apps/edit/components/content/section_controls/test/index.test.js
  src/client/apps/edit/components/content/sections/video/index.jsx
  src/client/apps/edit/components/content/sections/video/index.styl
  src/client/apps/edit/components/layout/index.styl
  src/client/apps/edit/index.styl
  src/client/components/remove_button/index.jsx
  src/client/components/remove_button/test/index.test.jsx
  yarn.lock
Labels: In progress

#1765 [VSCode] Update cSpell settings to be less intrusive
  .vscode/extensions.json
  .vscode/settings.json
Labels: In progress

#1766 Setup /edit2 route, new actions for text
  src/client/actions/edit/sectionActions.js
  src/client/actions/test/edit/sectionActions.test.js
  src/client/apps/edit/components/content/section_container/index.jsx
  src/client/apps/edit/components/content/section_list/index.jsx
  src/client/apps/edit/components/content/sections/news/EditSourceControls.tsx
  src/client/apps/edit/components/content/sections/text/index2.tsx
  src/client/apps/edit/index.coffee
  src/client/apps/edit/routes.coffee
  src/client/apps/edit/test/routes.test.coffee
  src/client/assets/main.coffee
Labels: In progress, Merge On Green

#1767 /Edit2 text utils updates
  package.json
  src/client/apps/edit/components/content/section_list/index.jsx
  src/client/apps/edit/components/content/section_list/test/index.test.jsx
  src/client/apps/edit/routes.coffee
  src/client/apps/edit/test/routes.test.coffee
  src/client/components/draft/components/text_nav.tsx
  src/client/components/draft/paragraph/paragraph.tsx
  src/client/components/draft/paragraph/test/paragraph.test.tsx
  src/client/components/draft/paragraph/utils/convert.tsx
  src/client/components/draft/paragraph/utils/test/utils.test.ts
  src/client/components/draft/paragraph/utils/utils.ts
  src/client/components/draft/rich_text/utils/convert.tsx
  src/client/components/draft/rich_text/utils/test/convert.test.ts
  src/client/components/draft/rich_text/utils/test/utils.test.ts
  src/client/components/draft/rich_text/utils/utils.ts
  src/client/components/draft/shared/decorators.tsx
  src/client/components/draft/shared/links.tsx
  src/client/components/draft/shared/selection.ts
  src/client/components/draft/shared/shared.ts
  src/client/components/draft/shared/test/decorators.test.tsx
  src/client/components/draft/shared/test/links.test.tsx
  src/client/components/draft/shared/test/selection.test.ts
  src/client/components/draft/shared/test/shared.test.ts
  src/client/components/draft/typings.ts
  yarn.lock
Labels: In progress

#1769 @damassi => linting updates
  .eslintrc
  package.json
  src/client/apps/edit/components/edit_container.jsx
  yarn.lock
Labels: In progress, Merge On Green

#1771 Section tool QA
  src/client/apps/edit/components/content/section_container/index.jsx
  src/client/apps/edit/components/content/section_container/test/index.test.js
  src/client/apps/edit/components/content/section_tool/index.jsx
  src/client/apps/edit/components/content/section_tool/index.styl
  src/client/apps/edit/components/content/section_tool/test/index.test.js
  src/client/apps/edit/components/icons.jade
  src/client/apps/edit/index.styl
  src/client/apps/edit/public/icons/edit_section_tool.svg
  src/client/apps/edit/public/icons/edit_section_tool_close.svg
Labels: In progress

#1772 @l2succes => Toolchain updates to match Reaction
  .babelrc
  package.json
  src/client/apps/display/test/routes.test.js
  src/client/apps/edit/components/admin/test/components/article/article_authors.test.js
  src/client/apps/edit/components/admin/test/components/article/index.test.js
  src/client/apps/edit/components/admin/test/components/super_article.test.js
  src/client/apps/edit/components/admin/test/index.test.js
  src/client/apps/edit/components/content/sections/related_articles/test/index.test.js
  src/client/apps/edit/components/test/edit_container.test.js
  src/client/components/autocomplete2/test/list_metaphysics.test.js
  src/client/components/rich_text/utils/decorators.js
  yarn.lock
Labels: In progress

#1773 [Text QA] Paragraph styles
  src/client/apps/edit/components/content/article_layouts/article.jsx
  src/client/apps/edit/components/content/sections/footer/index.jsx
  src/client/apps/edit/components/content/sections/footer/index.styl
  src/client/apps/edit/components/content/sections/footer/index.tsx
  src/client/apps/edit/components/content/sections/footer/test/index.test.tsx
  src/client/apps/edit/components/content/sections/images/components/edit_image.tsx
  src/client/apps/edit/components/content/sections/images/index.jsx
  src/client/apps/edit/components/content/sections/images/index.styl
  src/client/apps/edit/components/content/sections/images/test/edit_image.test.tsx
  src/client/apps/edit/components/content/sections/video/index.jsx
  src/client/apps/edit/index.styl
  src/client/components/drag_drop/test/index.test.coffee
Labels: In progress, Jira Synced

#1775 Move babel-plugin-lodash to dependencies
  package.json
Labels: In progress

#1776 Release
  package.json
Labels: In progress
