Repository artsy/positron, pull requests merged in 2019-02, with the labels that each got.

#1878 Refactor Drag & Drop component, change authors order
  package.json
  src/client/apps/edit/components/admin/components/article/article_authors.tsx
  src/client/apps/edit/components/content/section_controls/index.jsx
  src/client/apps/edit/components/content/section_controls/test/index.test.tsx
  src/client/apps/edit/components/content/sections/images/components/edit_image.tsx
  src/client/apps/edit/components/content/sections/images/index.styl
  src/client/apps/edit/components/content/sections/images/index.tsx
  src/client/apps/edit/components/content/sections/images/test/index.test.tsx
  src/client/apps/edit/index.styl
  src/client/components/autocomplete2/list.tsx
  src/client/components/autocomplete2/list_metaphysics.tsx
  src/client/components/drag_drop/test/drag_source.test.js
  src/client/components/drag_drop2/drag_source.tsx
  src/client/components/drag_drop2/drag_target.tsx
  src/client/components/drag_drop2/index.tsx
  src/client/components/drag_drop2/test/drag_source.test.tsx
  src/client/components/drag_drop2/test/drag_target.test.tsx
  src/client/components/drag_drop2/test/index.test.tsx
  test.config.js
  yarn.lock
Labels: Jira Synced, Merge On Green

#1889 Use palette collapse over deprecated StaticCollapse
  src/client/apps/edit/components/yoast/index.tsx
Labels: Merge On Green

#1894 [Text QA] Remove empty text sections while editing
  src/client/actions/edit/sectionActions.ts
  src/client/actions/test/edit/sectionActions.test.ts
  src/client/apps/edit/components/content/section_container/index.styl
  src/client/apps/edit/components/content/section_container/index.tsx
  src/client/apps/edit/components/content/section_container/test/index.test.tsx
  src/client/apps/edit/components/content/section_controls/index.styl
  src/client/apps/edit/components/content/section_list/index.jsx
  src/client/apps/edit/components/content/section_list/test/index.test.jsx
  src/client/apps/edit/components/content/sections/hero/index.jsx
  src/client/apps/edit/components/content/sections/hero/test/index.test.js
  src/client/apps/edit/components/content/sections/text/index.styl
  src/client/apps/edit/components/content/sections/text/index2.tsx
  src/client/apps/edit/components/edit_container.jsx
  src/client/apps/edit/index.styl
  yarn.lock
Labels: Jira Synced

#1896 Fix tests broken by Reaction's Input
  src/client/apps/edit/components/admin/components/article/test/article_authors.test.tsx
  src/client/apps/edit/components/admin/components/test/sponsor.test.tsx
  src/client/apps/edit/components/admin/components/test/super_article.test.tsx
  src/client/apps/edit/components/admin/components/test/tags.test.tsx
  src/client/apps/edit/components/content/sections/embed/test/controls.test.tsx
  src/client/apps/edit/components/content/sections/images/components/test/controls.test.tsx
  src/client/apps/edit/components/content/sections/images/components/test/input_artwork_url.test.tsx
  src/client/apps/edit/components/content/sections/social_embed/test/controls.test.tsx
  src/client/apps/edit/components/display/components/test/email.test.tsx
  src/client/apps/settings/client/curations/display/components/canvas/test/canvas_text.test.tsx
  src/client/apps/settings/client/curations/display/components/panel/test/index.test.tsx
  src/client/apps/settings/client/curations/display/components/test/campaign.test.tsx
  src/client/apps/settings/client/curations/gucci/test/metadata.test.tsx
  src/client/apps/settings/client/curations/gucci/test/section.test.tsx
  src/client/apps/settings/client/curations/gucci/test/series.test.tsx
  src/client/components/character_limit/test/index.test.tsx
Labels: Merge On Green

#1902 Add sponsor description/subtitle
  src/api/apps/articles/model/schema.coffee
  src/api/apps/articles/test/model/index/persistence.test.coffee
Labels: Jira Synced

#1905 Add a new section for News sitemap
  doc/distribution.md
  doc/images/google-news.png
Labels: Jira Synced, Merge On Green

#1859 [Related Articles] exclude related articles with unpublished media
  src/api/apps/articles/model/index.js
  src/api/apps/articles/model/retrieve.coffee
  src/api/apps/articles/model/retrieve.js
  src/api/apps/articles/test/model/retrieve.spec.js
  src/api/apps/articles/test/model/retrieve.test.coffee
  src/api/apps/graphql/resolvers.js
  src/api/apps/graphql/test/resolvers.spec.js
Labels: Jira Synced
